name: MCEngineArtifact
version: 1.0.0
main: com.github.mcengine.MCEngineArtifact
author: MCEngine
description: Items with abilities
depend: [HeadDatabase]
commands:
  material:
    description: "material command"
    usage: "/<command> <arg0> <arg1>"
    permission: "material.command"
    aliases:
      - material
  ashar: 
    description: "ashar command"
    usage: "/<command> <arg0> <arg1>"
    permission: "ashar.command"
    aliases:
      - ashar