name: MCEngineArtifact
version: 1.0.0
main: com.github.mcengine.MCEngineArtifact
author: MCEngine
description: Items with abilities
commands:
  ashar: 
    description: "ashar command"
    usage: "/<command> <arg0>"
    permission: "ashar.command"
    aliases:
      - ashar